### ISSUE TITLE
Create a 0.1.10 release

### ISSUE THREAD

**Issue by JohnAD** [ba0f3/scram.nim#12]
Mind adding a 0.1.10 release? The latest 0.1.9 release does not work with the newly released Nim version 1.2. However, the most recent commits fix the compatibility issues.

So, a new release will let `nimble` users see the compatible code.

And, for me, this would allow my `mongopool` library to require `scram` 0.1.10 which brings `mongopool` up to 1.2 compatibility also.

**Comment by ba0f3** [comment]
new release added, thank you!
