### ISSUE TITLE
Is scram.nim still operational?

### ISSUE THREAD

**Issue by JohnAD** [ba0f3/scram.nim#8]
I'm having considerable problems with the 'nimongo' library, which uses scram.nim for generating the authentication messages back and forth during SCRAM-SHA-1 authentication. I've created 3 accounts on different public MongoDB providers and am seeing the same problem with all three.

So, I dove down and started doing diagnostics; added "echo" statements all over the place to deduce the point of failure.

The information received back from `prepareFinalMessage` is being rejected by the servers.

I went ahead and found an equivalent algo on a python library and compared the results. Given the same password digest and first message (the unencoded payload), the python library returns a different result.

Looking even deeper, the python equivalent of line 55's:

```
saltedPassword = hi[T](password, salt, iterations)
```
is also returning a different result given the exact same inputs.

So, I was wondering if you are seeing any different behavior of the library when compiled with Nim's most recent standard libraries. (Among other things, the 'std/sha1' algorithm was changed completely back on October 9, 2018.)

I'll still keep looking for answers; but I figured I'd ask. Unfortunately the library does not have any unit tests to check against. I might do a PR with some once I get my bearings. Right now I've been diagnosing this for over 12 hours and my eyes are losing focus. <grin>

(Off-topic, sort of: on line 15 of utils.nim, the salt is appended with a 00 00 00 01. I assume this is because MongoDB tends to send a salt of 16 bytes instead of 20? Also, why the 01 at the end? I was under the impression that the algo called for all-zeroes for salt padding.)

**Comment by ba0f3** [comment]
I made this library when I worked w/ rethinkdb driver, since rethinkdb shutdown, I didn't have chance to use it anymore.

I will take a look later this weekend, also there is a code block in `scram/client.nim` that will execute when you compile it directly.

**Comment by ba0f3** [comment]
I just replace `sha1` w/ `std/sha1`, can you please try again?

**Comment by JohnAD** [comment]
Very sorry, I did not mean to imply that you should replace `sha1` with `std/sha1`. `sha1` already imports `std/sha1`. The latest commit breaks the library.

I simply meant that in October, the underlying `std/sha1` algorithm that `sha1` uses was changed. There is no way to undo that since the std libraries are part of Nim. (ref: https://github.com/nim-lang/Nim/pull/9242 )

**Comment by ba0f3** [comment]
oh I get it, lemme see what I can do
